# Generated by Django 5.0.7 on 2024-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Add subtitle for the subscription', null=True),
        ),
    ]
